service: inmodia

provider:
  name: aws
  runtime: python3.6
  stage: local
  environment: ${file(./env.${opt:stage, self:provider.stage}.yml)}

functions:
  run:
    handler: run.handler
    events:
      - schedule: rate(8 hours)

  clean:
    handler: run.clean
    events:
      - schedule: rate(30 days)

  sync:
    handler: run.sync

  delete:
    handler: run.delete

plugins:
  - serverless-python-requirements
